### ISSUE TITLE
Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

### ISSUE THREAD

**Issue by ixbcqq** [DustinWin/clash_singbox-tools#5]
Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

**Comment by DustinWin** [comment]
已解答，不要在不同项目问同一个问题。https://github.com/DustinWin/clash_singbox-tutorials/issues/27#issuecomment-2164834627
