### ISSUE TITLE
AX6000中升级sing-box-puernya内核后，在ShellCrash的更新菜单中看到的当前版本号怎么不一致

### ISSUE THREAD

**Issue by ceylog** [DustinWin/clash_singbox-tools#7]
如题，问题如下图，是ShellCrash获取版本号有问题还是编译构建的时候版本没有更新，纯好奇，不影响使用，强迫症犯了
<img width="663" alt="image" src="https://github.com/DustinWin/clash_singbox-tools/assets/1237383/ef759f47-0682-46cd-8f84-e63ff1fe5987">

<img width="1711" alt="image" src="https://github.com/DustinWin/clash_singbox-tools/assets/1237383/8ae18779-5ea0-4532-a195-ad468459356d">

**Comment by DustinWin** [comment]
通过定时任务或者说是直接替换 `$CRASHDIR/CrashCore.tar.gz` 文件的方法，“更新”里面的版本是不会变的。

**Comment by ceylog** [comment]
> 通过定时任务或者说是直接替换 `$CRASHDIR/CrashCore.tar.gz` 文件的方法，“更新”里面的版本是不会变的。

了解 感谢解答
