### ISSUE TITLE
请问clash是无法下载吗

### ISSUE THREAD

**Issue by 307yin** [DustinWin/clash_singbox-tools#8]

**Comment by DustinWin** [comment]
详细描述问题

**Comment by 307yin** [comment]
我想下载我们的linux版，但是点进来这个也页面是无法找到文件呢
![Uploading calsh.png…]()

**Comment by DustinWin** [comment]
你指的是这个？ https://github.com/DustinWin/clash_singbox-tools/tree/Clash-Premium

**Comment by 307yin** [comment]
是的谢谢 但是解压缩后只是乱码，我再看看
